[workspace]

members = ["amqprs", "amqp_serde", "examples", "benchmarks"]
rust-version = "1.60"
resolver = "2"

# [profile.bench]
# opt-level = 3
# debug = false
# lto = true
# codegen-units = 1


[workspace.dependencies]
serde_bytes_ng = { version = "0.1.2" }
